GET http://localhost:8080/app
###
GET http://localhost:8080/api/healthz
###
GET http://localhost:8080/admin/metrics
###
POST http://localhost:8080/admin/reset
###
POST http://localhost:8080/api/users
Content-Type: application/json

{
    "password": "test12345",
    "email": "bestfriend@salmon.com"
}
###
POST http://localhost:8080/api/login
Content-Type: application/json

{
    "password": "test12345",
    "email": "bestfriend@salmon.com"
}
###
POST http://localhost:8080/api/login
Content-Type: application/json

{
    "password": "wrongpassword",
    "email": "bestfriend@salmon.com"
}
###
POST http://localhost:8080/api/chirps
Content-Type: application/json

{
    "body": "Hello, World!",
    "user_id": "7d9e7fef-19f1-44b5-84ce-833ef310a212"
}
###
POST http://localhost:8080/api/chirps
Content-Type: application/json

{
    "body": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui libero, explicabo quas a labore repellendus, laboriosam veritatis suscipit consequuntur dicta eos ipsam ea, unde tempora voluptatem dignissimos ratione mollitia eum reiciendis. A atque itaque minima! Modi sapiente eligendi, cum sed consequuntur quas aspernatur culpa iste molestias facere inventore, corporis molestiae earum numquam, unde praesentium ducimus incidunt? Corrupti optio blanditiis vitae eos a laboriosam porro laborum natus nulla molestias itaque ipsam error facilis vero explicabo rerum deleniti enim sapiente accusamus odio, amet tempore laudantium. Esse delectus numquam totam quae ipsa saepe, molestiae tempora libero nisi dolorem dolorum iste, natus, doloremque a velit eos officia aperiam debitis expedita consequatur adipisci nam iure.",
    "user_id": "7d9e7fef-19f1-44b5-84ce-833ef310a212"
}
###
POST http://localhost:8080/api/chirps
Content-Type: application/json

{
    "body": "kerfuffle sharbert fornax this is what I say",
    "user_id": "7d9e7fef-19f1-44b5-84ce-833ef310a212"
}
###
POST http://localhost:8080/api/chirps
Content-Type: application/json

{
    "body": "kerfuffle! sharbert! fornax! this is what I really want to say!",
    "user_id": "7d9e7fef-19f1-44b5-84ce-833ef310a212"
}
###
POST http://localhost:8080/api/chirps
Content-Type: application/json

{
    "body": "I wonder how much I need to make a living?",
    "user_id": "7d9e7fef-19f1-44b5-84ce-833ef310a212"
}
###
GET http://localhost:8080/api/chirps
###
GET http://localhost:8080/api/chirps/caa7f570-2907-46d3-b35e-db01ca936a1d

###
GET http://localhost:8080/api/chirps/caa7f570-2907-46d3-b35e-db00ca825a2d